#!/usr/bin/env bash
# Generate TypeScript types for the frontend from the Python schema source.
# The frontend must never hand-define the wire shapes (X0.2).
#
# Pipeline: fessel_schemas.export emits a JSON Schema $defs document; that
# is converted to TS via json-schema-to-typescript (npx, no global install).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
out="$root/webui/shared/schemas.ts"
schema_tmp="$(mktemp -t fessel-schema.XXXXXX.json)"
trap 'rm -f "$schema_tmp"' EXIT

# Emit JSON Schema from the canonical Python models.
(cd "$root/schemas" && uv run python -m fessel_schemas.export) > "$schema_tmp"

mkdir -p "$root/webui/shared"

# Convert to TS. json-schema-to-typescript reads the $defs and emits one
# interface per definition.
npx --yes json-schema-to-typescript@15 \
  --input "$schema_tmp" \
  --output "$out" \
  --bannerComment "// GENERATED by tools/generate-types.sh from src/fessel/schemas — do not edit."

echo "wrote $out"
