#!/usr/bin/env python3
"""Emit Go structs for the webui from the exported per-model JSON Schema.

Called by generate-types.sh (see there for the pipeline). Only the models the
Go service AUTHORS are generated — pass-through bodies (supervisor responses)
stay untyped on purpose, since the Go layer must forward them verbatim,
unknown fields included.

The per-model export inlines dependencies with their `title` preserved, so
titled sub-objects (e.g. ModeTriplet inside Capabilities) and titled enums
(LiveViewErrorCode) are hoisted into named Go types and de-duplicated across
models. Output is deterministic (schema property order) so the Makefile
check-types staleness diff works.
"""

from __future__ import annotations

import json
import sys

HEADER = """\
// Code generated by tools/generate-types.sh from src/fessel/schemas. DO NOT EDIT.

// Package schemas holds the Go side of the shared wire contract: structs
// generated from the canonical pydantic models, used wherever the webui
// AUTHORS a response body (rather than passing a supervisor body through).
package schemas
"""


def go_name(snake: str) -> str:
  return "".join(part.capitalize() for part in snake.split("_"))


def scalar_type(schema: dict) -> str | None:
  return {"string": "string", "integer": "int", "number": "float64", "boolean": "bool"}.get(
    schema.get("type", "")
  )


class Generator:
  def __init__(self) -> None:
    self.emitted: dict[str, str] = {}  # title -> rendered block
    self.order: list[str] = []

  def field_type(self, schema: dict, owner: str, field: str) -> str:
    if "enum" in schema:
      title = schema.get("title") or f"{owner}{go_name(field)}"
      self.emit_enum(title, schema)
      return title
    if schema.get("type") == "array":
      return "[]" + self.field_type(schema.get("items", {}), owner, field)
    if schema.get("type") == "object" and "properties" in schema:
      title = schema.get("title") or f"{owner}{go_name(field)}"
      self.emit_struct(title, schema)
      return title
    t = scalar_type(schema)
    if t is None:
      raise SystemExit(
        f"generate_go_types: unsupported schema for {owner}.{field}: {json.dumps(schema)[:200]}"
      )
    return t

  def emit_enum(self, title: str, schema: dict) -> None:
    if title in self.emitted:
      return
    lines = [f"type {title} string", "", "const ("]
    for value in schema["enum"]:
      lines.append(f'  {title}{go_name(value)} {title} = "{value}"')
    lines.append(")")
    self.emitted[title] = "\n".join(lines)
    self.order.append(title)

  def emit_struct(self, title: str, schema: dict) -> None:
    if title in self.emitted:
      return
    self.emitted[title] = ""  # reserve slot against recursion; fill below
    self.order.append(title)
    required = set(schema.get("required", []))
    fields = []
    for name, sub in schema.get("properties", {}).items():
      # Nullable optionals arrive as anyOf [X, {type: null}]; unwrap to a
      # pointer so a nil marshals to JSON null, matching pydantic's output.
      pointer = name not in required
      if "anyOf" in sub:
        variants = [v for v in sub["anyOf"] if v.get("type") != "null"]
        if len(variants) != 1:
          raise SystemExit(f"generate_go_types: unsupported anyOf in {title}.{name}")
        sub = variants[0]
        pointer = True
      t = self.field_type(sub, title, name)
      star = "*" if pointer else ""
      fields.append(f'  {go_name(name)} {star}{t} `json:"{name}"`')
    body = "\n".join(fields) if fields else ""
    self.emitted[title] = f"type {title} struct {{\n{body}\n}}" if fields else f"type {title} struct{{}}"


def main() -> None:
  per_model_path, out_path, *models = sys.argv[1:]
  with open(per_model_path, encoding="utf-8") as fh:
    per_model = json.load(fh)
  gen = Generator()
  for model in models:
    if model not in per_model:
      raise SystemExit(f"generate_go_types: model {model!r} not in the export")
    gen.emit_struct(model, per_model[model])
  blocks = [gen.emitted[t] for t in gen.order]
  with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(HEADER + "\n" + "\n\n".join(blocks) + "\n")


if __name__ == "__main__":
  main()
