#!/usr/bin/env bash
# Generate TypeScript types AND runtime Zod validators for the frontend from
# the Python schema source. The frontend must never hand-define the wire
# shapes (X0.2); both artifacts come from one source so they cannot diverge.
#
# Pipeline: fessel_schemas.export emits a JSON Schema $defs document; that is
# converted to:
#   - webui/shared/schemas.ts    compile-time types (json-schema-to-typescript)
#   - webui/shared/validators.ts runtime validators  (json-schema-to-zod)
#
# Both run via the frontend's locally-installed tools (declared devDeps), so
# `make types` must be re-run after editing any model — the CI sync guard
# (Makefile `check-types`) fails the build if the committed output is stale.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
fe="$root/webui/frontend"
types_out="$root/webui/shared/schemas.ts"
# Validators import `zod` (a frontend runtime dep), so they live INSIDE the
# frontend where that resolves — unlike schemas.ts, which is dependency-free
# and genuinely shared. Both are generated from the one Python source.
zod_out="$fe/src/generated/validators.ts"
work="$(mktemp -d -t fessel-schema.XXXXXX)"
trap 'rm -rf "$work"' EXIT

schema_tmp="$work/bundle.json"
per_model="$work/per-model.json"

# Emit JSON Schema from the canonical Python models: a bundled doc for the TS
# generator and a per-model map for the Zod generator (see export.py).
(cd "$root/schemas" && uv run python -m fessel_schemas.export) > "$schema_tmp"
(cd "$root/schemas" && uv run python -m fessel_schemas.export --per-model) > "$per_model"

mkdir -p "$root/webui/shared" "$(dirname "$zod_out")"
banner="// GENERATED by tools/generate-types.sh from src/fessel/schemas — do not edit."

# The converters are devDependencies of the frontend; resolve them from there
# (npm ci installs them) so this never pulls an unpinned package ad hoc.
( cd "$fe"

  # Types: one interface per $defs entry from the bundled doc.
  npx --no-install json-schema-to-typescript \
    --input "$schema_tmp" \
    --output "$types_out" \
    --bannerComment "$banner"

  # Validators: one named Zod schema per model (<Model>Schema). Each model is
  # emitted from its own self-contained schema so cross-model refs resolve
  # (StateResponse embeds PlugState). --depth is high enough to inline refs
  # rather than fall back to z.any().
  {
    echo "$banner"
    echo 'import { z } from "zod";'
    echo ""
    # Iterate model names from the per-model map, in document order.
    for name in $(node -e 'const m=require(process.argv[1]); console.log(Object.keys(m).join(" "))' "$per_model"); do
      node -e 'const m=require(process.argv[1]); process.stdout.write(JSON.stringify(m[process.argv[2]]))' "$per_model" "$name" > "$work/$name.json"
      npx --no-install json-schema-to-zod \
        --input "$work/$name.json" \
        --name "${name}Schema" \
        --depth 10 \
        --noImport
      echo ""
    done
  } > "$zod_out"
)

# Go structs for the models the Go webui AUTHORS (pass-through bodies stay
# untyped on purpose — the Go layer forwards supervisor responses verbatim).
# Extend the model list when the Go service starts authoring another shape.
go_out="$root/webui/internal/schemas/schemas_gen.go"
mkdir -p "$(dirname "$go_out")"
(cd "$root/schemas" && uv run python "$here/generate_go_types.py" "$per_model" "$go_out" \
  ModeTriplet Capabilities LiveViewError)
gofmt -w "$go_out"

echo "wrote $types_out"
echo "wrote $zod_out"
echo "wrote $go_out"
