// GENERATED by tools/generate-types.sh from src/fessel/schemas — do not edit.

/**
 * "<W>x<H>", e.g. "1280x720"
 */
export type Resolution = string;
export type Fps = number;
export type BitrateBps = number;
export type Modes = ModeTriplet[];
export type Path = string;
export type Path1 = string;
export type LiveStateValue = "off" | "starting" | "running" | "stopping";
export type Path2 = string | null;

export interface FesselSchemas {
  ModeTriplet?: ModeTriplet;
  Capabilities?: Capabilities;
  LiveActivate?: LiveActivate;
  LiveDeactivate?: LiveDeactivate;
  LiveState?: LiveState;
  [k: string]: unknown;
}
/**
 * A concrete video operating point.
 *
 * `resolution` is the canonical "<W>x<H>" string; fps and bitrate_bps are
 * integers. The full canonical form (incl. fps and bitrate) is produced by
 * mode_to_canonical and is what travels in the WHEP `mode` query parameter
 * and the signed token.
 */
export interface ModeTriplet {
  resolution: Resolution;
  fps: Fps;
  bitrate_bps: BitrateBps;
  [k: string]: unknown;
}
/**
 * Retained payload on arm/video/capabilities.
 */
export interface Capabilities {
  modes: Modes;
  [k: string]: unknown;
}
/**
 * Payload of arm/video/cmd/live/activate.
 */
export interface LiveActivate {
  path: Path;
  mode: ModeTriplet;
  [k: string]: unknown;
}
/**
 * Payload of arm/video/cmd/live/deactivate.
 */
export interface LiveDeactivate {
  path: Path1;
  [k: string]: unknown;
}
/**
 * Retained payload on arm/video/state/live.
 */
export interface LiveState {
  state: LiveStateValue;
  path?: Path2;
  mode?: ModeTriplet | null;
  [k: string]: unknown;
}
