// GENERATED by tools/generate-types.sh from src/fessel/schemas — do not edit.

/**
 * "<W>x<H>", e.g. "1280x720"
 */
export type Resolution = string;
export type Fps = number;
export type BitrateBps = number;
export type MaxLookbackSeconds = number;
export type LiveStateValue = "off" | "starting" | "running" | "stopping";
export type Path = string | null;
/**
 * Error codes of a rejected POST /whep (webui relay, architecture §2.3).
 */
export type LiveViewErrorCode =
  "live_unavailable" | "live_timeout" | "live_activation_failed" | "live_error" | "whep_negotiate_failed";
export type Reason = string;
export type On = boolean | null;
export type Verified = boolean;
export type VerifiedAt = string | null;
export type Up = boolean | null;
/**
 * video's explicit-recording branch state machine (V4.3).
 *
 * Separate from the live branch's LiveStateValue: the two branches share the
 * encoder hardware but are independent. `idle` is the at-rest state (no
 * recording), mirroring the live branch's `off`.
 */
export type RecordingStateValue = "idle" | "starting" | "recording" | "stopping";
export type ActiveRecordingId = string | null;
export type StartedAt = string | null;
export type Id = string;
export type StartedAt1 = string;
export type EndedAt = string | null;
export type Operator = string | null;
export type DurationSeconds = number | null;
export type Segments = number | null;
export type FlaggedForUpload = boolean;
/**
 * Where a recording is in the flag-for-upload pipeline (V4.6/V4.7).
 *
 * `none` — never flagged. `queued` — marker written, uploader not yet acting.
 * `uploading` — transfer in progress. `uploaded` — in MinIO, marker deleted.
 * `failed` — non-retryable failure; marker renamed `.failed`.
 */
export type UploadStateValue = "none" | "queued" | "uploading" | "uploaded" | "failed";
export type UploadedAt = string | null;
export type RecordingId = string;
/**
 * Where a recording is in the flag-for-upload pipeline (V4.6/V4.7).
 *
 * `none` — never flagged. `queued` — marker written, uploader not yet acting.
 * `uploading` — transfer in progress. `uploaded` — in MinIO, marker deleted.
 * `failed` — non-retryable failure; marker renamed `.failed`.
 */
export type UploadStateValue1 = "none" | "queued" | "uploading" | "uploaded" | "failed";
export type Attempts = number;
export type LastAttemptAt = string | null;
export type LastError = string | null;
export type Count = number;
export type OldestPendingSeconds = number | null;
export type Healthy = boolean | null;
export type RecordingId1 = string;
export type StartedAt2 = string;
export type EndedAt1 = string | null;
export type DurationSeconds1 = number | null;
export type Operator1 = string | null;
export type FlaggedForUpload1 = boolean;
/**
 * Where a recording is in the flag-for-upload pipeline (V4.6/V4.7).
 *
 * `none` — never flagged. `queued` — marker written, uploader not yet acting.
 * `uploading` — transfer in progress. `uploaded` — in MinIO, marker deleted.
 * `failed` — non-retryable failure; marker renamed `.failed`.
 */
export type UploadStateValue2 = "none" | "queued" | "uploading" | "uploaded" | "failed";
export type ActivityScoreEma = number;
export type LastFrameAt = string | null;
export type Healthy1 = boolean;
export type LevelDb = number | null;
export type Healthy2 = boolean;
export type Ts = string;
/**
 * The discrete anomaly events the Slice-5 detectors emit (and clear).
 *
 * `safe_box_violation` — foreground motion outside the configured safe box.
 * `rest_violation` — motion during a rest period (between episodes / paused).
 * `audio_spike` — a sound-level spike above baseline. The `*_cleared` variants
 * are the self-clearing return-to-normal events the Slice-6 state machine wants
 * to see paired with the entry.
 */
export type AnomalyType =
  | "safe_box_violation"
  | "safe_box_cleared"
  | "rest_violation"
  | "rest_violation_cleared"
  | "audio_spike"
  | "audio_spike_cleared";
export type AnomalyRecordingId = string | null;
export type Cleared = boolean;
export type Component = string;
export type Supervisor = string | null;
export type Video = string | null;
/**
 * Abbreviated supervisor safety state (architecture §2.4).
 *
 * Slice 3 only ever holds whatever the operator's last command implies; the
 * real transitions land in Slice 6. The full set is declared here so the
 * enum doesn't have to change later.
 */
export type SafetyState =
  "INIT" | "IDLE" | "RUNNING" | "PAUSED" | "STOPPED" | "SHUTDOWN_ARM" | "SHUTDOWN_JETSON" | "DEGRADED";
export type Jetson = {
  [k: string]: unknown;
} | null;
export type RecentAnomalies = AnomalyLogEntry[];

export interface FesselSchemas {
  ModeTriplet?: ModeTriplet;
  Capabilities?: Capabilities;
  LiveActivate?: LiveActivate;
  LiveDeactivate?: LiveDeactivate;
  LiveState?: LiveState;
  LiveViewError?: LiveViewError;
  PlugState?: PlugState;
  CameraState?: CameraState;
  RecordingState?: RecordingState;
  RecordingMetadata?: RecordingMetadata;
  UploadProgress?: UploadProgress;
  UploadBacklog?: UploadBacklog;
  RecordingListItem?: RecordingListItem;
  VisionState?: VisionState;
  AudioState?: AudioState;
  AnomalyLogEntry?: AnomalyLogEntry;
  VersionState?: VersionState;
  StateResponse?: StateResponse;
  [k: string]: unknown;
}
/**
 * A concrete video operating point.
 *
 * `resolution` is the canonical "<W>x<H>" string; fps and bitrate_bps are
 * integers. The full canonical form (incl. fps and bitrate) is produced by
 * mode_to_canonical; recordings use it (the live path is a fixed profile).
 */
export interface ModeTriplet {
  resolution: Resolution;
  fps: Fps;
  bitrate_bps: BitrateBps;
  [k: string]: unknown;
}
/**
 * Retained payload on arm/video/capabilities.
 *
 * `recording_mode` is the operating point the deploy is configured to record
 * with (from `video.recording` config, §2.2) — recording resolution is a deploy
 * setting, not a per-request choice, so the operator UI no longer picks it.
 * `max_lookback_seconds` is how far a recording can reach back into the always-on
 * ring buffer (= the ring window); the record dialog uses it to bound its
 * look-back timeline.
 */
export interface Capabilities {
  recording_mode: ModeTriplet;
  max_lookback_seconds: MaxLookbackSeconds;
  [k: string]: unknown;
}
/**
 * Payload of arm/video/cmd/live/activate.
 *
 * Parameterless (architecture §2.2): the live profile is a deploy-time config
 * setting on video, not a per-session parameter. The message carries no
 * fields; it means "a viewer wants the live stream; attach the sender."
 */
export interface LiveActivate {
  [k: string]: unknown;
}
/**
 * Payload of arm/video/cmd/live/deactivate. Parameterless.
 */
export interface LiveDeactivate {
  [k: string]: unknown;
}
/**
 * Retained payload on arm/video/state/live.
 */
export interface LiveState {
  state: LiveStateValue;
  path?: Path;
  mode?: ModeTriplet | null;
  [k: string]: unknown;
}
/**
 * Error body of a rejected POST /whep.
 *
 * Authored by the Go webui (generated Go struct) and consumed by the
 * frontend's WHEP client (generated Zod validator), so both ends of the
 * live-view error contract derive from this one definition.
 */
export interface LiveViewError {
  error: LiveViewErrorCode;
  reason: Reason;
  [k: string]: unknown;
}
/**
 * A WiZ plug's last *verified* state (S3.1/S3.3).
 *
 * `on` reflects the state read back via getPilot after the last action or
 * background refresh — not the last command issued. `verified` is False when
 * the most recent verify failed (the command may have been sent but could not
 * be confirmed); `verified_at` is the ISO-8601 timestamp of that read.
 */
export interface PlugState {
  on?: On;
  verified?: Verified;
  verified_at?: VerifiedAt;
  [k: string]: unknown;
}
/**
 * Camera up/down, derived from the retained arm/video/state/* topics.
 */
export interface CameraState {
  up?: Up;
  [k: string]: unknown;
}
/**
 * Retained payload on arm/video/state/recording (V4.5).
 *
 * The single source of truth for "is a recording active right now"; the
 * dashboard derives its Start/Stop button from this (via supervisor /state).
 */
export interface RecordingState {
  state?: RecordingStateValue;
  active_recording_id?: ActiveRecordingId;
  started_at?: StartedAt;
  [k: string]: unknown;
}
/**
 * The per-recording metadata.json written on finalisation (V4.4).
 *
 * `flagged_for_upload` and `upload_state` are mutable in place: flag-upload
 * (V4.5) and the uploader (V4.7) rewrite this file. It is the recording's
 * source of truth for the rest of the system (listing, playback routing).
 */
export interface RecordingMetadata {
  id: Id;
  started_at: StartedAt1;
  ended_at?: EndedAt;
  operator?: Operator;
  mode?: ModeTriplet | null;
  duration_seconds?: DurationSeconds;
  segments?: Segments;
  flagged_for_upload?: FlaggedForUpload;
  upload_state?: UploadStateValue;
  uploaded_at?: UploadedAt;
  [k: string]: unknown;
}
/**
 * Payload on arm/video/upload/<recording-id> (V4.7), surfaced read-only by
 * the backend (B4.6) so the dashboard can show per-recording upload status.
 */
export interface UploadProgress {
  recording_id: RecordingId;
  state?: UploadStateValue1;
  attempts?: Attempts;
  last_attempt_at?: LastAttemptAt;
  last_error?: LastError;
  [k: string]: unknown;
}
/**
 * Upload-queue health gauges (V4.8): how many markers are pending and how
 * old the oldest one is. The Slice 7 ">3h" P2 alert lands against these.
 *
 * `healthy` is the uploader's own liveness, derived from heartbeat freshness
 * (arm/video/upload/heartbeat), NOT from queue depth: an uploader that never
 * started (or is crash-looping before it ever publishes anything) has
 * count=0/oldest=None too, indistinguishable from a genuinely idle uploader
 * unless liveness is tracked separately. None = no heartbeat ever received.
 */
export interface UploadBacklog {
  count?: Count;
  oldest_pending_seconds?: OldestPendingSeconds;
  healthy?: Healthy;
  [k: string]: unknown;
}
/**
 * One row of supervisor GET /recordings (S4.4) — what's on the Pi.
 *
 * A projection of RecordingMetadata sufficient for the dashboard list; segment
 * URLs are decided by the backend (B4.2/B4.3), not enumerated here.
 */
export interface RecordingListItem {
  recording_id: RecordingId1;
  started_at: StartedAt2;
  ended_at?: EndedAt1;
  duration_seconds?: DurationSeconds1;
  operator?: Operator1;
  flagged_for_upload?: FlaggedForUpload1;
  upload_state?: UploadStateValue2;
  [k: string]: unknown;
}
/**
 * The `vision` field of supervisor /state (S5.2).
 *
 * `healthy` is supervisor's interpretation of the vision heartbeat: false when
 * the heartbeat is stale OR when its `last_frame_at` has stopped advancing (a
 * wedged capture keeps the process heartbeating while no frames flow). Not a
 * separate safety state, just a flag Slice 6 reads.
 */
export interface VisionState {
  activity_score_ema?: ActivityScoreEma;
  last_frame_at?: LastFrameAt;
  healthy?: Healthy1;
  [k: string]: unknown;
}
/**
 * The `audio` field of supervisor /state (S5.2).
 */
export interface AudioState {
  level_db?: LevelDb;
  healthy?: Healthy2;
  [k: string]: unknown;
}
/**
 * One entry of supervisor's bounded in-memory anomaly log (S5.1/S5.3).
 *
 * `payload` is the full original event so the dashboard can show details;
 * `anomaly_recording_id` links to the evidence recording if one was created.
 * `cleared` flips true when the matching `*_cleared` event arrives.
 */
export interface AnomalyLogEntry {
  ts: Ts;
  type: AnomalyType;
  anomaly_recording_id?: AnomalyRecordingId;
  cleared?: Cleared;
  payload?: Payload;
  [k: string]: unknown;
}
export interface Payload {
  [k: string]: unknown;
}
/**
 * The `version` field of supervisor /state (health-check spec §2.1).
 *
 * `component` is the AUTHORITATIVE Pi-side version used for the cluster/Pi
 * compatibility comparison (all Pi components ship in one dpkg, so one version
 * covers them). `supervisor`/`video` are optional per-process details, useful in
 * the drill-down only if they ever diverge (e.g. a partial upgrade). The strings
 * are semver-shaped MAJOR.MINOR.PATCH; the comparison uses MAJOR.MINOR only.
 */
export interface VersionState {
  component: Component;
  supervisor?: Supervisor;
  video?: Video;
  [k: string]: unknown;
}
/**
 * Body of supervisor GET /state and backend GET /api/state (S3.3).
 *
 * `jetson` is whatever the Jetson's GET /state returned (opaque to the
 * backend and dashboard — supervisor caches it and passes it through);
 * `null` when the Jetson has not been reached yet.
 *
 * Slice 4 adds `recording` (the retained recording-state topic, cached) and
 * `upload_backlog` (the V4.8 gauges, cached) so the dashboard's recording
 * controls and backlog indicator read from the same /state poll as the rest.
 *
 * Slice 5 adds `vision` and `audio` (live sensing values + health) and
 * `recent_anomalies` (a short tail of the in-memory anomaly log), so the
 * dashboard's sensing strip and recent-anomalies panel read from the same poll.
 */
export interface StateResponse {
  safety_state?: SafetyState;
  jetson?: Jetson;
  plugs?: Plugs;
  camera?: CameraState;
  recording?: RecordingState;
  upload_backlog?: UploadBacklog;
  vision?: VisionState;
  audio?: AudioState;
  recent_anomalies?: RecentAnomalies;
  version?: VersionState | null;
  [k: string]: unknown;
}
export interface Plugs {
  [k: string]: PlugState;
}
