// Code generated by tools/generate-types.sh from src/fessel/schemas. DO NOT EDIT.

// Package schemas holds the Go side of the shared wire contract: structs
// generated from the canonical pydantic models, used wherever the webui
// AUTHORS a response body (rather than passing a supervisor body through).
package schemas

type ModeTriplet struct {
	Resolution string `json:"resolution"`
	Fps        int    `json:"fps"`
	BitrateBps int    `json:"bitrate_bps"`
}

type Capabilities struct {
	Modes []ModeTriplet `json:"modes"`
}

type LiveViewError struct {
	Error  LiveViewErrorCode `json:"error"`
	Reason string            `json:"reason"`
}

type LiveViewErrorCode string

const (
	LiveViewErrorCodeLiveUnavailable      LiveViewErrorCode = "live_unavailable"
	LiveViewErrorCodeLiveTimeout          LiveViewErrorCode = "live_timeout"
	LiveViewErrorCodeLiveActivationFailed LiveViewErrorCode = "live_activation_failed"
	LiveViewErrorCodeLiveError            LiveViewErrorCode = "live_error"
	LiveViewErrorCodeWhepNegotiateFailed  LiveViewErrorCode = "whep_negotiate_failed"
)
